package com.example.music_mobile_app.manager.AuthManager.constant;

public class ConstantVariable {
    public static String ACCESS_TOKEN = "BQCUTXRuhtJ7qpUdc9NdCrLM_hTBnnJ0YgqpgXhJsqN9CpYcydHjSUNe1zV8bAoS3mNS_tTynb6hbBGAqoi_q6MW125oI8YPzWZ4lCwvzO0i-lF59ZaYcAbksehhhmJpMRpdOF9DMueeahfv4e83ageRDIhuKmuvQslgzhDfUyYhta1vKw9raWUVkSY40YfFE7xqOHLGbS2QUxidjpYwvmUyTDmxcXrw5PTm35myzASQ0UHeqsMr0BAgtr8hGiOpyRLbKfYEitGQwat7eo-2";

    public static String USER_ID = "8fp3lkzd33nnx2r8zfthp9w5b";
}
